# Generated by Django 5.1.1 on 2024-09-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0003_item_icon_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='icon',
        ),
    ]
