# Generated by Django 5.1.1 on 2024-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0004_remove_item_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market_data',
            name='average_price',
        ),
        migrations.RemoveField(
            model_name='market_data',
            name='current_average_price',
        ),
        migrations.RemoveField(
            model_name='market_data',
            name='min_price',
        ),
        migrations.AddField(
            model_name='market_data',
            name='units_sold',
            field=models.IntegerField(null=True),
        ),
    ]
