# Generated by Django 5.1.1 on 2024-09-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0005_remove_market_data_average_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market_data',
            old_name='item',
            new_name='item_ref',
        ),
        migrations.RenameField(
            model_name='market_data',
            old_name='world',
            new_name='world_ref',
        ),
    ]
