# Generated by Django 5.1.1 on 2024-09-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0006_rename_item_market_data_item_ref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market_data',
            old_name='item_ref',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='market_data',
            old_name='world_ref',
            new_name='world',
        ),
    ]
