# Generated by Django 5.1.1 on 2024-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0007_rename_item_ref_market_data_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
