# Generated by Django 5.1.1 on 2024-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0008_alter_market_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
