# Generated by Django 5.1.1 on 2024-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0009_alter_market_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_sale_velocity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='item',
            name='market_data_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='market_data',
            name='price_per_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market_data',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market_data',
            name='regular_sale_velocity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='market_data',
            name='tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market_data',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market_data',
            name='units_sold',
            field=models.IntegerField(default=0),
        ),
    ]
