# Generated by Django 5.1.1 on 2024-09-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0010_item_average_sale_velocity_item_market_data_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dc_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='item',
            name='region_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
