# Generated by Django 5.1.1 on 2024-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0013_remove_item_dc_high_world_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_daily_transactions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
