# Generated by Django 5.1.1 on 2024-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0018_item_potential_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_data',
            name='history_entries',
            field=models.IntegerField(default=0),
        ),
    ]
