# Generated by Django 5.1.1 on 2024-09-09 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0019_market_data_history_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='average_daily_transactions',
        ),
        migrations.RemoveField(
            model_name='item',
            name='average_items_per_transaction',
        ),
        migrations.RemoveField(
            model_name='item',
            name='average_sale_velocity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dc_delta',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dc_low_world',
        ),
        migrations.RemoveField(
            model_name='item',
            name='market_data_list',
        ),
        migrations.RemoveField(
            model_name='item',
            name='potential_profit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='region_delta',
        ),
        migrations.RemoveField(
            model_name='item',
            name='region_low_world',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.CreateModel(
            name='Item_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_sale_velocity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_daily_transactions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_items_per_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('market_data_list', models.TextField(default='')),
                ('region_delta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dc_delta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('potential_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dc_low_world', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_dl', to='delta_checker.world')),
                ('region_low_world', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_rl', to='delta_checker.world')),
            ],
        ),
    ]
