# Generated by Django 5.1.1 on 2024-09-09 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0020_remove_item_average_daily_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_stats',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='delta_checker.item'),
        ),
    ]
