# Generated by Django 5.1.1 on 2024-09-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0021_item_stats_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_stats',
            name='item',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
