# Generated by Django 5.1.1 on 2024-09-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0022_alter_item_stats_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_stats',
            name='dc_low_world',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item_stats',
            name='region_low_world',
            field=models.CharField(max_length=256),
        ),
    ]
