# Generated by Django 5.1.1 on 2024-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta_checker', '0024_alter_item_stats_dc_low_world_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_stats',
            name='id',
        ),
        migrations.AlterField(
            model_name='item_stats',
            name='item',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
